# Generated by Django 4.0.2 on 2022-02-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_view',
            new_name='upload',
        ),
    ]
