# Generated by Django 4.0.2 on 2022-02-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_upload_new_owner_upload_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
