# Generated by Django 4.0.2 on 2022-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_upload_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='upload',
            name='origin',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='upload',
            name='previous_owner',
            field=models.CharField(default=models.CharField(max_length=64), max_length=64),
        ),
    ]
