# Generated by Django 4.0.2 on 2022-02-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_alter_upload_code_alter_upload_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='new_owner',
            field=models.CharField(max_length=64),
        ),
    ]
